### ISSUE TITLE
main - Unknown mode. Aborting.

### ISSUE THREAD

**Issue by DeepBhuptani** [bkerler/edl#153]
I tried many commands but everytime I am getting unknown mode. I am using Realme XT in EDL mode since this is the only mode I can boot in apart from its stock recovery. Even bootloader/fastboot mode is not showing up in my phone. Please help me if I am doing something wrong.

![image](https://user-images.githubusercontent.com/63183860/133779167-a6bbf30b-b94c-4830-8dc2-9ea19440f6ae.png)

**Comment by HighlanderUkUk** [comment]
Boot into stock recovery and select language, then tap the version number a few times and it will bring up a box for you to put phone into edl mode

**Comment by DeepBhuptani** [comment]
Yes, I am in EDL mode but how do I interact with it?
I want to flash stock ROM from EDL mode.
I have compatible OFP firmware and I also have extracted it to get its firehose loader.
I tried with QFIL but it gives me sahara download fail error everytime.
Any suggestion to flash Stock ROM through EDL??

**Comment by bhaskarbalaji5** [comment]
I'm having the same problem, with the same console output. (I was initially surprised that I had to install a different driver rather than the QC 9008 one, but doing so didn't improve things, as I still get "Unknown mode. Aborting." either way.) I'm on Windows 10, trying to access a Pixel (2016). Is this just a problem with not having the right loader? I see Loaders/qualcomm/factory/msm8996Pro which is the right chipset, but I guess those still might not be right for my phone.

The device shows up on device manager with the 9008 driver (or QUSB_BULK otherwise), so I thought it is in EDL mode (but it's hard bricked). I also see the device with PID 9008 with UsbDk.

I don't mean to derail -- was just hoping it was more context for the same issue since I'm seeing the same thing.

**Comment by HighlanderUkUk** [comment]
Have you tried using the live dvd?

**Comment by bkerler** [comment]
Make sure the loader you use matches the pkhash of your device. Otherwise it will fail as it's not signed correctly. You can't just use "any" loader for the same chipset, not even for unfused devices as the hardware has to match.

**Comment by bhaskarbalaji5** [comment]
I haven't actually managed to find a Pixel loader anywhere else on the internet; I was just naively hoping that one of them saved here might be right (and would be picked automatically). Sounds like a no-go, as I honestly expected, if indeed the "Unknown mode" error can result from just not having the right loader.

Is the live DVD just like a boot disc or something? I haven't heard of it related to this effort. (I am ultimately just trying to read a few files in internal storage, not write anything to the device.)

**Comment by HighlanderUkUk** [comment]
The live dvd is like a boot disk and link can be found in the readme for this repo

**Comment by DeepBhuptani** [comment]
> Have you tried using the live dvd?

Yes, same mentioned problem with liveDVD as well.
I am using the loader for the correct model Realme XT since I have extracted loader from its stoke ROM.
Is there any possibility of erasing/removing any partition of the devices and we ran into this issue?

**Comment by bkerler** [comment]
Not using edlclient. You need to use factory oppo tools.
